name: Lynn Valley Today
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6090634048450738
title: Lynn Valley Today
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d2b2c'
    - '#697986'
    - '#8fabc3'
    - '#e5ded6'
  brandStrength: 0.8703458113595843
  lightness: 0.3473845305852592
  saturation: 0.929729632101953
  rhythmicContrast: 0.08420610707253218
purpose: []
